name: Homebrew

on:
  - workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Build Oatmeal
        run: brew install eigenhombre/brew/oatmeal
      - name: Test Oatmeal
        run: oatmeal create app parentheses
      - name: Install Quicklisp
        run: oatmeal-quicklisp-install
      - name: Build app 
        working-directory: parentheses
        run: make
      - name: Test App
        working-directory: parentheses
        run: ./parentheses
