name: Homebrew

on:
  - workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Build
        run: brew install eigenhombre/brew/oatmeal
      - name: Test Oatmeal
        run: oatmeal create app parentheses
      - name: Test App
        run: ./parentheses
