name: Homebrew

on:
  - workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Build Oatmeal
        run: brew install eigenhombre/brew/oatmeal
      - name: Test Oatmeal
        run: oatmeal create app parentheses
        env:
           LISP_HOME: .
      - name: Fetch Quicklisp
        run: curl -s -o quicklisp.lisp http://beta.quicklisp.org/quicklisp.lisp
#       - name: Build app 
#         working-directory: parentheses
#         run: make
#       - name: Test App
#         working-directory: parentheses
#         run: ./parentheses
