name: CD
on:
  workflow_dispatch:
  push:
   tags:
     - '*'
jobs:
  release-osx:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Release
      run: echo TESTING
